language: generic
sudo: required

services:
  - docker

script:
  - ./dist/build_all.sh

deploy:
  provider: script
  script: ./dist/docker_push.sh
  on:
    branch: release


# publish:
#   - ./dist/docker_push.sh
